name: Build artifacts and create release

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install . pyinstaller
    - run: pyinstaller pyinstaller/autotorrent.spec
    - run: cd dist && tar -czvf ../pyinstaller-${{ matrix.os }}.tar.gz *
      if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
    - run: cd dist && zip -r ../pyinstaller-${{ matrix.os }}.zip *
      shell: bash
      if: ${{ matrix.os == 'windows-latest' }}
    - uses: actions/upload-artifact@v3
      with:
        name: pyinstaller-${{ matrix.os }}
        path: pyinstaller-${{ matrix.os }}.*

  build-shiv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install shiv
    - run: mkdir dist
    - run: shiv -c at2 -o dist/at2.pyz autotorrent2
    - uses: actions/upload-artifact@v3
      with:
        name: zipapp-shiv
        path: dist/at2.pyz

  create-release:
    runs-on: ubuntu-latest
    needs: [build-pyinstaller, build-shiv]
    steps:
      - name: Download shiv
        uses: actions/download-artifact@v3
        with:
          name: zipapp-shiv
      - name: Download pyinstaller linux
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-ubuntu-latest
      - name: Download pyinstaller macos
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-macos-latest
      - name: Download pyinstaller windows
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-windows-latest
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: TODO
          files: |
            at2.pyz
            pyinstaller-linux-latest.tar.gz
            pyinstaller-macos-latest.tar.gz
            pyinstaller-windows-latest.tar.gz